spring:
  datasource:
    url: jdbc:mysql://localhost:3306/searchems_db?serverTimezone=America/Argentina/Cordoba&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true&useSSL=false
    username: searchems_dev
    password: dlctpi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        jdbc:
          batch_size: 300
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    include-binding-errors: always
    include-message: always
searchems:
  endpoint:
    base-url: http://localhost:8080